# Step 7.2: persistence has no GUI dependency; the window tier is optional.
target_sources(adi_core PRIVATE src/adi/ui/window_state.cpp src/adi/ui/project_document.cpp)
add_executable(adi_ui_document_tests tests/test_ui_document.cpp)
target_link_libraries(adi_ui_document_tests PRIVATE adi_core adi_warnings)
add_test(NAME adi_ui_document_tests COMMAND adi_ui_document_tests)
add_executable(adi_ui_window_state_tests tests/test_ui_window_state.cpp)
target_link_libraries(adi_ui_window_state_tests PRIVATE adi_core adi_warnings)
add_test(NAME adi_ui_window_state_tests COMMAND adi_ui_window_state_tests)
if(ADI_WITH_JUCE)
    # JUCE's generated resource/artefact paths exceed MAX_PATH in deep worktrees.
    if(WIN32)
        string(LENGTH "${CMAKE_BINARY_DIR}" adi_ui_path_length)
        if(adi_ui_path_length GREATER 100)
            message(FATAL_ERROR "Step 7 JUCE build needs a short Windows build path (under 100 characters).")
        endif()
    endif()
    add_library(adi_ui_shell STATIC src/juce/ui_shell.cpp)
    target_link_libraries(adi_ui_shell PUBLIC adi_settings juce::juce_gui_basics)
    target_compile_definitions(adi_ui_shell PUBLIC JUCE_STANDALONE_APPLICATION=1 JUCE_USE_CURL=0 JUCE_WEB_BROWSER=0)
    juce_add_console_app(adi_ui_shell_tests PRODUCT_NAME "adi_ui_shell_tests")
    target_sources(adi_ui_shell_tests PRIVATE tests/test_ui_shell.cpp)
    target_link_libraries(adi_ui_shell_tests PRIVATE adi_ui_shell)
    target_compile_definitions(adi_ui_shell_tests PRIVATE ADI_UI_REFERENCES="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/ui")
    # Apply our warning policy to our code, not JUCE's module translation units.
    set_source_files_properties(src/juce/ui_shell.cpp tests/test_ui_shell.cpp PROPERTIES
        COMPILE_OPTIONS "$<TARGET_PROPERTY:adi_warnings,INTERFACE_COMPILE_OPTIONS>")
    add_test(NAME adi_ui_shell_tests COMMAND adi_ui_shell_tests)
    juce_add_gui_app(adi_app PRODUCT_NAME "ADI" COMPANY_NAME "ADI" BUNDLE_ID "org.adi.daw")
    target_sources(adi_app PRIVATE src/juce/ui_main.cpp src/juce/juce_device_loader.cpp src/juce/vst3_host.cpp src/juce/vst3_events.cpp)
    # Reuse the player's host-format/ASIO switches, not its console entry or fixture.
    get_target_property(adi_ui_host_defs adi_play COMPILE_DEFINITIONS)
    list(FILTER adi_ui_host_defs EXCLUDE REGEX "^(_CONSOLE|ADI_TEST_VST3)")
    target_compile_definitions(adi_app PRIVATE ${adi_ui_host_defs})
    target_link_libraries(adi_app PRIVATE adi_ui_shell juce::juce_audio_processors juce::juce_audio_utils juce::juce_audio_devices)
    set_source_files_properties(src/juce/ui_main.cpp PROPERTIES COMPILE_OPTIONS "$<TARGET_PROPERTY:adi_warnings,INTERFACE_COMPILE_OPTIONS>")
endif()
