# SPDX-License-Identifier: GPL-3.0-or-later
target_sources(adi_core PRIVATE src/adi/dsp/chorus_ensemble.cpp)
add_executable(adi_chorus_ensemble_tests tests/test_chorus_ensemble.cpp)
target_link_libraries(adi_chorus_ensemble_tests PRIVATE adi_core adi_warnings)
add_test(NAME adi_chorus_ensemble_tests COMMAND adi_chorus_ensemble_tests)
if(ADI_WITH_PD)
    target_sources(adi_pd_builtins PRIVATE src/adi/pd_builtins/chorus_ensemble_tilde.cpp)
    add_executable(adi_chorus_ensemble_pd_tests tests/test_chorus_ensemble_pd.cpp)
    target_link_libraries(adi_chorus_ensemble_pd_tests PRIVATE adi_core adi_warnings)
    target_compile_definitions(adi_chorus_ensemble_pd_tests PRIVATE ADI_PD_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd" ADI_DEVICE_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd/devices")
    add_test(NAME adi_chorus_ensemble_pd_tests COMMAND adi_chorus_ensemble_pd_tests)
endif()
