# SPDX-License-Identifier: GPL-3.0-or-later
target_sources(adi_core PRIVATE src/adi/dsp/live_delay.cpp)
add_executable(adi_delay_tests tests/test_delay.cpp)
target_link_libraries(adi_delay_tests PRIVATE adi_core adi_warnings)
add_test(NAME adi_delay_tests COMMAND adi_delay_tests)
if(ADI_WITH_PD)
    target_sources(adi_pd_builtins PRIVATE src/adi/pd_builtins/delay_tilde.cpp)
    add_executable(adi_delay_pd_tests tests/test_delay_pd.cpp)
    target_link_libraries(adi_delay_pd_tests PRIVATE adi_core adi_warnings)
    target_compile_definitions(adi_delay_pd_tests PRIVATE ADI_PD_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd" ADI_DELAY_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd/devices")
    add_test(NAME adi_delay_pd_tests COMMAND adi_delay_pd_tests)
endif()
