# SPDX-License-Identifier: GPL-3.0-or-later
target_sources(adi_core PRIVATE src/adi/dsp/hybrid_reverb.cpp)
add_executable(adi_hybrid_reverb_tests tests/test_hybrid_reverb.cpp)
target_link_libraries(adi_hybrid_reverb_tests PRIVATE adi_core adi_warnings)
add_test(NAME adi_hybrid_reverb_tests COMMAND adi_hybrid_reverb_tests)
if(ADI_WITH_PD)
    target_sources(adi_pd_builtins PRIVATE src/adi/pd_builtins/hybrid_reverb_tilde.cpp)
    add_executable(adi_hybrid_reverb_pd_tests tests/test_hybrid_reverb_pd.cpp)
    target_link_libraries(adi_hybrid_reverb_pd_tests PRIVATE adi_core adi_warnings)
    target_compile_definitions(adi_hybrid_reverb_pd_tests PRIVATE ADI_PD_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd" ADI_HYBRID_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd/devices")
    add_test(NAME adi_hybrid_reverb_pd_tests COMMAND adi_hybrid_reverb_pd_tests)
endif()
