# SPDX-License-Identifier: GPL-3.0-or-later
target_sources(adi_core PRIVATE src/adi/dsp/utility.cpp)
add_executable(adi_utility_tests tests/test_utility.cpp)
target_link_libraries(adi_utility_tests PRIVATE adi_core adi_warnings)
add_test(NAME adi_utility_tests COMMAND adi_utility_tests)
if(ADI_WITH_PD)
    target_sources(adi_pd_builtins PRIVATE src/adi/pd_builtins/utility_tilde.cpp)
    add_executable(adi_utility_pd_tests tests/test_utility_pd.cpp)
    target_link_libraries(adi_utility_pd_tests PRIVATE adi_core adi_warnings)
    target_compile_definitions(adi_utility_pd_tests PRIVATE ADI_PD_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd" ADI_DEVICE_PATCH_DIR="${CMAKE_CURRENT_SOURCE_DIR}/pd/devices")
    add_test(NAME adi_utility_pd_tests COMMAND adi_utility_pd_tests)
endif()
