// SPDX-License-Identifier: GPL-3.0-or-later
//
// Which registry keys answer each row of docs/SETTINGS-CATALOGUE.md, and why
// the other rows are not settings (ADR-0156). Row names are the catalogue's:
// "<section> / <setting up to its first ' ('>".

#include "adi/settings/catalogue.hpp"

namespace adi::settings {

const char* toString(Absence a) {
    switch (a) {
        case Absence::Rejected:    return "rejected";
        case Absence::Note:        return "note";
        case Absence::NotASetting: return "not a setting";
        case Absence::Backlog:     return "backlog";
        case Absence::Wish:        return "wish";
    }
    return "?";
}

const std::vector<AnsweredRow>& answeredRows() {
    static const std::vector<AnsweredRow> rows = {
        {"1. Display & Input / Language",
         {"lookfeel.language"}},
        {"1. Display & Input / Outline View in Focus",
         {"lookfeel.focusOutline"}},
        {"1. Display & Input / Scroll bars",
         {"lookfeel.scrollBars"}},
        {"1. Display & Input / Follow behavior",
         {"lookfeel.followPlayhead", "lookfeel.followMode"}},
        {"1. Display & Input / Show user interface labels",
         {"lookfeel.showLabels"}},
        {"1. Display & Input / Use Tab Key to Move Focus",
         {"lookfeel.tabMovesFocus"}},
        {"1. Display & Input / Wrap Tab Navigation",
         {"lookfeel.wrapTabNavigation"}},
        {"1. Display & Input / Move Clips with Arrow Keys",
         {"editing.arrowKeysMoveClips"}},
        {"1. Display & Input / Pen Tablet Mode",
         {"lookfeel.penTabletMode"}},
        {"1. Display & Input / Permanent Scrub Areas",
         {"lookfeel.permanentScrubAreas"}},
        {"1. Display & Input / Zoom on Selection",
         {"lookfeel.zoomOnSelection"}},
        {"1. Display & Input / Knob / slider / value-box modes",
         {"lookfeel.knobMode", "lookfeel.valueBoxMode", "lookfeel.sliderMode"}},
        {"1. Display & Input / Mouse wheel changes parameters",
         {"lookfeel.wheelChangesParameters"}},
        {"1. Display & Input / Tooltips",
         {"lookfeel.showInfoView", "lookfeel.showTooltips", "lookfeel.tooltipDelayMs"}},
        {"2. Theme & Colors / Theme",
         {"lookfeel.theme"}},
        {"2. Theme & Colors / Palette tone",
         {"lookfeel.paletteTone"}},
        {"2. Theme & Colors / High contrast",
         {"lookfeel.contrast"}},
        {"2. Theme & Colors / Grid line intensity",
         {"lookfeel.gridIntensity"}},
        {"2. Theme & Colors / Brightness, color intensity, hue",
         {"lookfeel.brightness", "lookfeel.colorIntensity", "lookfeel.hue"}},
        {"2. Theme & Colors / Auto-assign track colors",
         {"lookfeel.autoTrackColor"}},
        {"2. Theme & Colors / Clip color",
         {"lookfeel.clipColor"}},
        {"2. Theme & Colors / Accent colour",
         {"lookfeel.accentColor"}},
        {"2. Theme & Colors / Track-type default colours",
         {"lookfeel.trackColor.audio", "lookfeel.trackColor.midi", "lookfeel.trackColor.instrument", "lookfeel.trackColor.group", "lookfeel.trackColor.return", "lookfeel.trackColor.master", "lookfeel.trackColor.vca"}},
        {"2. Theme & Colors / Waveform display",
         {"lookfeel.waveformPerceptual", "lookfeel.waveformBrightness"}},
        {"2. Theme & Colors / Event volume curve and fades display",
         {"lookfeel.showVolumeCurves", "lookfeel.showFades", "lookfeel.volumeHandle"}},
        {"2. Theme & Colors / Meter appearance",
         {"lookfeel.showMeterPeakHold", "lookfeel.meterPeakHoldMs", "lookfeel.meterDecayDbPerSecond", "lookfeel.meterStickyClip", "lookfeel.meterFloorDb"}},
        {"3. Audio / Driver Type",
         {"audio.driverType"}},
        {"3. Audio / Audio Input Device / Audio Output Device",
         {"audio.inputDevice", "audio.outputDevice"}},
        {"3. Audio / Channel Configuration",
         {"audio.channelConfig", "audio.outputRoles"}},
        {"3. Audio / In/Out Sample Rate",
         {"audio.sampleRate", "project.sampleRate"}},
        {"3. Audio / Resample silently when rates differ",
         {"audio.silentResampling"}},
        {"3. Audio / Default SR & Pitch Conversion",
         {"audio.srcQuality"}},
        {"3. Audio / Buffer Size",
         {"audio.bufferSize"}},
        {"3. Audio / Driver Error Compensation",
         {"audio.driverErrorCompensationMs"}},
        {"3. Audio / Test Tone, Tone Volume, Tone Frequency, CPU Usage Simulator",
         {"audio.testTone", "audio.testToneVolumeDb", "audio.testToneFrequencyHz", "audio.cpuSimulatorPercent"}},
        {"3. Audio / Loopback input",
         {"audio.loopbackSource"}},
        {"3. Audio / Close device when the app is inactive",
         {"audio.releaseDeviceInBackground"}},
        {"3. Audio / Warn when a device cannot be opened",
         {"audio.fallbackToSystemDevice"}},
        {"3. Audio / Auto-bypass plug-ins whose PDC exceeds a threshold when armed",
         {"audio.recordPdcThresholdMs"}},
        {"3. Audio / Linux audio backend and JACK transport",
         {"audio.linuxBackend", "audio.jackTransportSync"}},
        {"3. Audio / Automatic mute at a dB limit",
         {"audio.autoMute", "audio.autoMuteLimitDb"}},
        {"4. Link / Show Link Toggle",
         {"sync.showLinkToggle"}},
        {"4. Link / Start Stop Sync",
         {"sync.linkStartStopSync"}},
        {"4. Link / PTP",
         {"sync.ptpEnabled", "sync.ptpDomain", "sync.ptpAdapters", "sync.ptpGrandmasters"}},
        {"5. Tempo & MIDI / Control Surface 1-6: Control Surface / Input / Output / Dump",
         {"midi.autoAddControllers", "midi.controlSurfaceScripts"}},
        {"5. Tempo & MIDI / Takeover Mode",
         {"midi.takeoverMode"}},
        {"5. Tempo & MIDI / Master Focus Dial",
         {"midi.focusDialPort", "midi.focusDialChannel", "midi.focusDialCc", "midi.focusDialMode"}},
        {"5. Tempo & MIDI / MIDI Ports: Track",
         {"midi.port.track"}},
        {"5. Tempo & MIDI / MIDI Ports: Sync",
         {"midi.port.sync"}},
        {"5. Tempo & MIDI / MIDI Ports: Remote",
         {"midi.port.remote"}},
        {"5. Tempo & MIDI / MIDI Ports: MPE",
         {"midi.port.mpe"}},
        {"5. Tempo & MIDI / Per port: MIDI Clock Sync Delay",
         {"midi.port.clockSyncDelayMs"}},
        {"5. Tempo & MIDI / Per port: Sync Type",
         {"midi.port.syncType"}},
        {"5. Tempo & MIDI / Per port: MTC Frame Rate, MTC Start Offset",
         {"midi.port.mtcFrameRate", "midi.port.mtcStartOffset"}},
        {"5. Tempo & MIDI / Chase events",
         {"midi.chaseControllers", "midi.chasePitchBend", "midi.chaseProgramChange"}},
        {"5. Tempo & MIDI / MIDI Thru, Reset on Stop, Insert Reset Events after Record",
         {"midi.resetOnStop", "midi.insertResetAfterRecord"}},
        {"5. Tempo & MIDI / MIDI Filter",
         {"midi.recordFilter", "midi.thruFilter"}},
        {"6. File & Folder / Sample Editor",
         {"files.sampleEditor", "files.sampleEditorOpens"}},
        {"6. File & Folder / Decoding Cache: Minimum Free Space, Maximum Cache Size, Cache Folder, Cleanup",
         {"cache.maxSizeMb", "cache.minFreeSpaceMb", "cache.folder"}},
        {"6. File & Folder / Default projects folder, default render folder, default record folder",
         {"files.projectsFolder", "files.renderFolder", "library.recordFolder"}},
        {"6. File & Folder / Copy imported media into the project folder",
         {"files.copyImportedMedia"}},
        {"6. File & Folder / Open last project on startup; start-up template",
         {"files.openOnStart", "files.startTemplate"}},
        {"7. Library / Installation folder for Packs",
         {"library.contentFolders"}},
        {"7. Library / User Library location",
         {"library.userLibrary"}},
        {"7. Library / Collect Files on Export",
         {"library.collectOnExport"}},
        {"7. Library / Browser scan behaviour",
         {"library.backgroundIndexing", "library.maxResults"}},
        {"8. Plug-Ins / Rescan Plug-Ins",
         {"plugins.scanOutOfProcess"}},
        {"8. Plug-Ins / Use VST3 Plug-In System Folders / Custom Folder + Browse",
         {"plugins.useVst3SystemFolders", "plugins.vst3Folders"}},
        {"8. Plug-Ins / CLAP folders",
         {"plugins.clapFolders", "plugins.lv2Folders"}},
        {"8. Plug-Ins / Prefer CLAP over VST3 when both are installed",
         {"plugins.preferClap"}},
        {"8. Plug-Ins / Auto-Open Plug-In Windows",
         {"plugins.autoOpenWindows"}},
        {"8. Plug-Ins / Multiple Plug-In Windows",
         {"plugins.multipleWindows"}},
        {"8. Plug-Ins / Auto-Hide Plug-In Windows",
         {"plugins.autoHideWindows"}},
        {"8. Plug-Ins / Plug-in editors always on top",
         {"plugins.editorsAlwaysOnTop"}},
        {"8. Plug-Ins / Plug-in window scaling",
         {"plugins.windowScale"}},
        {"8. Plug-Ins / VST parameter automation notifications",
         {"plugins.ignoreBroadcasts"}},
        {"8. Plug-Ins / AudioGridder servers",
         {"sync.audioGridderDiscovery"}},
        {"9. Record, Warp & Launch / File Type",
         {"record.writeBext", "record.writeIxml"}},
        {"9. Record, Warp & Launch / Exclusive Arm, Exclusive Solo",
         {"record.exclusiveArm", "record.exclusiveSolo"}},
        {"9. Record, Warp & Launch / Clip Update Rate",
         {"record.clipUpdateRate"}},
        {"9. Record, Warp & Launch / Start Playback with Record",
         {"record.startPlaybackWithRecord"}},
        {"9. Record, Warp & Launch / Loop/Warp Short Samples",
         {"record.shortSampleMode"}},
        {"9. Record, Warp & Launch / Auto-Warp Long Samples",
         {"record.importAutoWarp"}},
        {"9. Record, Warp & Launch / Default Warp Mode",
         {"record.defaultWarpMode"}},
        {"9. Record, Warp & Launch / Create Fades on Clip Edges",
         {"record.importEdgeFades"}},
        {"9. Record, Warp & Launch / Record quantization default",
         {"record.quantize"}},
        {"9. Record, Warp & Launch / Auto-arm on select",
         {"record.autoArmOnSelect"}},
        {"9. Record, Warp & Launch / Retrospective capture",
         {"record.retrospectiveSeconds"}},
        {"9. Record, Warp & Launch / Keep Monitoring Latency in Recorded Audio",
         {"audio.keepMonitoringLatency"}},
        {"9. Record, Warp & Launch / Loop recording: takes, discard incomplete",
         {"record.discardIncompleteTakes", "record.completeTakePercent"}},
        {"10. Licenses & Updates / Automatic updates",
         {"updates.checkOnLaunch"}},
        {"10. Licenses & Updates / Usage data",
         {"privacy.usageStatistics", "privacy.diagnosticLog"}},
        {"10. Licenses & Updates / Crash reports",
         {"privacy.crashReports"}},
        {"10. Licenses & Updates / Beta / early access",
         {"updates.channel"}},
        {"1. Cubase 15 Preferences / Editing",
         {"editing.autoSelectUnderCursor", "editing.deleteOverlaps", "editing.clipsGetTrackNames", "editing.trackFollowsClipSelection", "editing.automationFollowsClips", "editing.dragDelayMs"}},
        {"1. Cubase 15 Preferences / Editing — Audio",
         {"editing.wheelForVolumeAndFades", "editing.mutedClipsAsDeleted", "editing.importOptions", "editing.bounceReplaces"}},
        {"1. Cubase 15 Preferences / Editing — Tool Modifiers",
         {"editing.modifierPreset"}},
        {"1. Cubase 15 Preferences / Editing — Zoom",
         {"editing.zoomInRuler", "lookfeel.zoomOnSelection"}},
        {"1. Cubase 15 Preferences / Editors",
         {"editing.editorOpensIn", "editing.editorFollowsSelection"}},
        {"1. Cubase 15 Preferences / Event Display",
         {"music.pitchNaming", "lookfeel.gridIntensity", "lookfeel.waveformBrightness"}},
        {"1. Cubase 15 Preferences / General",
         {"files.defaultAuthor", "files.openOnStart"}},
        {"1. Cubase 15 Preferences / MIDI",
         {"midi.extendEarlyNotes"}},
        {"1. Cubase 15 Preferences / Metering",
         {"lookfeel.meterPeakHoldMs", "lookfeel.meterDecayDbPerSecond"}},
        {"1. Cubase 15 Preferences / Record",
         {"record.snapMidiPartsToBars", "record.retrospectiveSeconds"}},
        {"1. Cubase 15 Preferences / Transport",
         {"transport.windSpeed", "transport.locateOnClick"}},
        {"1. Cubase 15 Preferences / User Interface",
         {"lookfeel.theme", "lookfeel.accentColor", "lookfeel.autoTrackColor"}},
        {"1. Cubase 15 Preferences / VST",
         {"mixing.defaultSendLevelDb", "mixing.groupMuteMutesSources"}},
        {"2. Bitwig Studio Settings / Behavior",
         {"record.importAutoWarp", "record.warpDetectTempoChanges", "record.warpInsertFrom", "files.openOnStart", "updates.channel"}},
        {"2. Bitwig Studio Settings / Audio",
         {"audio.driverType", "audio.inputDevice", "audio.outputDevice", "audio.sampleRate", "audio.bufferSize", "audio.outputRoles"}},
        {"2. Bitwig Studio Settings / Controllers",
         {"midi.takeoverMode", "midi.autoAddControllers", "midi.controlSurfaceScripts"}},
        {"2. Bitwig Studio Settings / Synchronization",
         {"sync.clockSource", "sync.tempoResponsiveness", "midi.port.clockSyncDelayMs"}},
        {"2. Bitwig Studio Settings / Shortcuts",
         {"shortcuts.preset", "shortcuts.computerMidiKeyboard"}},
        {"2. Bitwig Studio Settings / User Interface",
         {"lookfeel.language", "lookfeel.contrast", "lookfeel.followPlayhead", "lookfeel.waveformPerceptual"}},
        {"2. Bitwig Studio Settings / Recording",
         {"record.autoArmOnSelect", "record.quantize"}},
        {"2. Bitwig Studio Settings / Locations",
         {"files.projectsFolder", "library.userLibrary", "midi.controlSurfaceScripts", "library.contentFolders", "plugins.vst3Folders", "plugins.clapFolders", "plugins.preferClap"}},
        {"3. REAPER Preferences / General: undo",
         {"transport.commitFieldsAfterPause", "files.projectsFolder", "lookfeel.tooltipDelayMs"}},
        {"3. REAPER Preferences / Project",
         {"newtrack.faderGainDb", "newtrack.showInMixer", "newtrack.meterMode", "newtrack.sendLevelDb", "newtrack.showEnvelopes", "files.startTemplate"}},
        {"3. REAPER Preferences / Audio",
         {"mixing.soloInFront", "mixing.soloInFrontDb", "mixing.soloBus", "audio.metronomeOutput", "audio.autoMute", "audio.releaseDeviceInBackground", "audio.recordPdcThresholdMs"}},
        {"3. REAPER Preferences / Buffering",
         {"transport.seekOnClick", "transport.runFxWhenStoppedMs", "transport.stopAtProjectEnd"}},
        {"3. REAPER Preferences / Appearance",
         {"lookfeel.gridIntensity", "lookfeel.brightness", "lookfeel.waveformPerceptual", "lookfeel.meterFloorDb"}},
        {"3. REAPER Preferences / Editing Behavior",
         {"editing.cursorFollowsSelection", "editing.linkLoopToSelection", "editing.transientSensitivity", "editing.rippleLockedClips", "editing.splitAllWithNoSelection"}},
        {"3. REAPER Preferences / Media",
         {"music.middleC"}},
        {"3. REAPER Preferences / Plug-ins",
         {"plugins.autoOpenWindows", "plugins.autoHideWindows", "plugins.clapFolders", "plugins.lv2Folders"}},
        {"3. REAPER Preferences / Project and file management",
         {"lookfeel.hiDpi", "lookfeel.dialogPosition"}},
        {"1. Engine / Block size and the granted size",
         {"audio.bufferSize"}},
        {"1. Engine / Compensation headroom",
         {"engine.compensationHeadroomSamples"}},
        {"1. Engine / Sample-rate conversion quality",
         {"audio.srcQuality"}},
        {"1. Engine / Delay compensation threshold when recording",
         {"audio.recordPdcThresholdMs"}},
        {"2. Sync / Link",
         {"sync.linkEnabled", "sync.showLinkToggle", "sync.linkStartStopSync"}},
        {"2. Sync / MIDI clock and MTC, in and out, per port, with offsets",
         {"sync.clockSource", "sync.tempoResponsiveness", "midi.port.sync", "midi.port.syncType", "midi.port.clockSyncDelayMs", "midi.port.mtcFrameRate", "midi.port.mtcStartOffset"}},
        {"2. Sync / LAN audio node",
         {"sync.lanJitterBufferMs", "sync.lanCodec", "sync.lanBitrateKbps"}},
        {"2. Sync / PTP",
         {"sync.ptpEnabled", "sync.ptpDomain", "sync.ptpAdapters", "sync.ptpGrandmasters"}},
        {"2. Sync / AudioGridder servers",
         {"sync.audioGridderDiscovery"}},
        {"3. AI agent / Tier",
         {"agent.tier"}},
        {"3. AI agent / Rate cap",
         {"agent.maxOpsPerMinute", "agent.maxOpsPerRequest"}},
        {"3. AI agent / Endpoint",
         {"agent.endpoint"}},
        {"3. AI agent / Stem separation and other async services",
         {"agent.asyncServices", "agent.resultsFolder"}},
        {"4. Windows and views / View states",
         {"windows.defaultView", "lookfeel.followMode"}},
        {"4. Windows and views / Undocking",
         {"windows.rememberFloatingPerDisplay"}},
        {"4. Windows and views / History",
         {"windows.snapshotName"}},
        {"4. Windows and views / Pd device analyser view",
         {"devices.pdAnalyserOpen"}},
        {"5. Music / Tuning",
         {"music.defaultTuning"}},
        {"5. Music / Pitch naming",
         {"music.pitchNaming", "music.middleC"}},
        {"5. Music / Default time signature, tempo, PPQ display",
         {"music.defaultTempo", "music.defaultTimeSignature"}},
        {"6. Devices and DSP / Pure Data",
         {"devices.pdExternalsFolders", "devices.pdPatchFolder"}},
        {"6. Devices and DSP / Freeze",
         {"devices.freezeTailSeconds", "devices.freezeMutedClipsSilent"}},
    };
    return rows;
}

const std::vector<AbsentRow>& absentRows() {
    static const std::vector<AbsentRow> rows = {
        {"4. What ADI does not need a setting for / Auto-save interval, number of auto-save files, project backups", Absence::NotASetting,
         "every op is committed as it happens (ADR-0003): there is no unsaved state and nothing to schedule; a snapshot is a File-menu command"},
        {"4. What ADI does not need a setting for / Maximum undo steps, maximum undo memory, save undo history with project, allow load of undo history", Absence::NotASetting,
         "the history is the project (ADR-0030): no step limit and no memory to cap; compaction is a command"},
        {"4. What ADI does not need a setting for / Store multiple redo paths", Absence::NotASetting,
         "branches are the model (ADR-0068): always kept"},
        {"4. What ADI does not need a setting for / Reduce CPU use of silent tracks; do not process muted tracks", Absence::NotASetting,
         "signal-driven suspension is always on (ADR-0043); the opt-out is the device's Always process switch"},
        {"4. What ADI does not need a setting for / Plug-in bridging, crash isolation, \"Terminate immediately if a plug-in corrupts the heap\"", Absence::Rejected,
         "sandboxing rejected for latency and complexity (ADR-0047)"},
        {"4. What ADI does not need a setting for / Anticipative FX processing, media buffering, advanced disk I/O", Absence::NotASetting,
         "the engine runs large blocks (ADR-0042, ADR-0102); a thread count arrives with the worker pool"},
        {"4. What ADI does not need a setting for / Deactivate Punch In on Stop, MIDI Max. Feedback, Run Setup on Create New Project", Absence::Note,
         "small behaviours decided by each feature's parity checklist (ADR-0108)"},
        {"1. Display & Input / Zoom Display", Absence::NotASetting,
         "zoom is per window, set in the window itself (ADR-0129 d3-d4)"},
        {"1. Display & Input / Restore \"Don't Show Again\" warnings", Absence::NotASetting,
         "a button that restores the warnings, not a value"},
        {"3. Audio / Input Latency / Output Latency / Overall Latency", Absence::NotASetting,
         "measured and shown, in samples and ms, never set"},
        {"3. Audio / Virtual audio device", Absence::NotASetting,
         "install state and status are shown; the endpoint names are fixed (ADR-0119)"},
        {"4. Link / Link Audio: Audio", Absence::NotASetting,
         "LAN audio is a device with its own panel (ADR-0126); its defaults are the Sync page's LAN row, and Link Audio itself is a wish"},
        {"4. Link / Link Audio: Name, Latency, Sync to Incoming Audio, peers list", Absence::Wish,
         "only if Link Audio is ever licensed (ADR-0126)"},
        {"5. Tempo & MIDI / Show Tempo Follower Toggle", Absence::Wish,
         "Tempo Follower is a P2 feature; the setting arrives with it"},
        {"5. Tempo & MIDI / Tempo Follower: Input Channel", Absence::Wish,
         "arrives with Tempo Follower"},
        {"5. Tempo & MIDI / Resync External Hardware: Show Resync Button", Absence::Backlog,
         "arrives with external sync (P2)"},
        {"5. Tempo & MIDI / MIDI-CI support", Absence::Wish,
         "MIDI-CI when the OS stacks expose it"},
        {"5. Tempo & MIDI / MIDI file import/export options", Absence::Backlog,
         "MIDI file options belong to the export dialog (P2)"},
        {"6. File & Folder / Create Analysis Files", Absence::NotASetting,
         "analysis is always cached; the cache is on this page"},
        {"6. File & Folder / Temporary Folder", Absence::NotASetting,
         "a new project is a file from its first op (ADR-0003); the default projects folder takes the slot"},
        {"6. File & Folder / Max Application", Absence::Rejected,
         "no Max for Live; Pure Data is the patching device (ADR-0035)"},
        {"6. File & Folder / Save project file references with relative paths", Absence::NotASetting,
         "paths are always relative and media is never embedded (ADR-0127)"},
        {"7. Library / Show Downloadable Packs", Absence::Rejected,
         "no store"},
        {"7. Library / Show Splice, Show Cloud, Show Push", Absence::Rejected,
         "no third-party services in the browser (ADR-0104)"},
        {"7. Library / Splice download folder", Absence::Rejected,
         "not applicable: no Splice"},
        {"7. Library / Preview settings", Absence::NotASetting,
         "the preview controls live in the browser, not in Settings"},
        {"7. Library / Export and import library metadata", Absence::NotASetting,
         "an export and an import command, not a value (ADR-0145 d11)"},
        {"8. Plug-Ins / Use Audio Units v2 / v3", Absence::Rejected,
         "no Audio Units (ADR-0041)"},
        {"8. Plug-Ins / Use VST2 Plug-In System Folders / Custom Folder + Browse", Absence::Rejected,
         "no VST2 (ADR-0015, ADR-0041)"},
        {"8. Plug-Ins / Plug-in blocks in the device view", Absence::NotASetting,
         "the panel rule is fixed, exactly as Live's (ADR-0150); Configure edits a device's panel"},
        {"8. Plug-Ins / Warn before removing a modified effect", Absence::Rejected,
         "removal is an op and undo restores it (ADR-0003)"},
        {"8. Plug-Ins / Create a MIDI track when loading an instrument", Absence::Rejected,
         "an instrument is a device on a MIDI track, Live's model"},
        {"8. Plug-Ins / Blocklist", Absence::NotASetting,
         "a list the scan writes; the page shows it with Re-enable"},
        {"9. Record, Warp & Launch / Bit Depth", Absence::NotASetting,
         "every recording is 32-bit float (ADR-0132 d1); export depths are chosen in the export dialog"},
        {"9. Record, Warp & Launch / Count-In", Absence::NotASetting,
         "Count-In lives in the metronome menu, as in Live 12"},
        {"9. Record, Warp & Launch / Record Session automation in", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"9. Record, Warp & Launch / Default Launch Mode", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"9. Record, Warp & Launch / Default Launch Quantization", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"9. Record, Warp & Launch / Select on Launch", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"9. Record, Warp & Launch / Select Next Scene on Launch", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"9. Record, Warp & Launch / Start Recording on Scene Launch", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"9. Record, Warp & Launch / Save Current Set as Default / Clear", Absence::NotASetting,
         "a command: save the current project as the default"},
        {"9. Record, Warp & Launch / Auto monitoring mode", Absence::NotASetting,
         "a track's monitor option, with tapemachine as a fourth; not global"},
        {"10. Licenses & Updates / Authorization", Absence::NotASetting,
         "the page shows the licences; there is nothing to authorise (ADR-0015)"},
        {"1. Cubase 15 Preferences / VST — Control Room", Absence::Backlog,
         "the Control Room is a v2 backlog (R-23, ADR-0125 d5)"},
        {"1. Cubase 15 Preferences / VariAudio and Video", Absence::NotASetting,
         "audio is always extracted from video; the warnings are one-time dialogs"},
        {"1. Cubase 15 Preferences / Customizing", Absence::NotASetting,
         "workspaces are views (ADR-0112), profiles are presets, Safe Mode is R-06"},
        {"1. Cubase 15 Preferences / Optimizing Audio Performance", Absence::NotASetting,
         "a performance panel that shows, not sets (R-24); no ASIO-Guard is needed (ADR-0042)"},
        {"2. Bitwig Studio Settings / Plug-ins", Absence::Rejected,
         "hosting modes rejected (ADR-0047); its per-plug-in list is the model for ADI's overrides"},
        {"1. Engine / ASIO path", Absence::NotASetting,
         "no raw bypass and no switch for one (ADR-0145 d5)"},
        {"1. Engine / Suspension", Absence::NotASetting,
         "always on, no global off (ADR-0043); the page shows how many nodes sleep"},
        {"1. Engine / Processing threads", Absence::Backlog,
         "a thread count arrives with the worker pool (ADR-0102 d4)"},
        {"1. Engine / Denormals", Absence::NotASetting,
         "flushed for the callback (ADR-0042 d6)"},
        {"1. Engine / Virtual device and loopback", Absence::NotASetting,
         "install state, endpoint names, driver version and signature are shown, not set"},
        {"1. Engine / Performance panel", Absence::NotASetting,
         "a panel that shows, not sets (R-24)"},
        {"3. AI agent / What the agent may read and change", Absence::NotASetting,
         "fixed by structure: the agent's whitelist and its never-list (ADR-0125 R-07, ADR-0152)"},
        {"4. Windows and views / Session View window", Absence::Backlog,
         "arrives with Session View (ADR-0101)"},
        {"4. Windows and views / Project tabs", Absence::NotASetting,
         "an inactive tab is always offline (ADR-0134 d1)"},
        {"5. Music / Buses", Absence::NotASetting,
         "64 buses, no cables (ADR-0113); the page says so"},
        {"6. Devices and DSP / Native DSP nodes", Absence::Note,
         "the built-in devices have nothing to set (ADR-0062)"},
        {"6. Devices and DSP / Racks and macros", Absence::Backlog,
         "macro curve defaults arrive with racks (ADR-0060)"},
    };
    return rows;
}

}  // namespace adi::settings
