#!/usr/bin/env python3
"""Generate adi_daw's Pd modules -- ADR-0096.

    python adi_daw/tools/gen_pd_patches.py            write adi_daw/pd/*.pd
    python adi_daw/tools/gen_pd_patches.py --check    exit 1 if they are stale

Generated, not hand-written, because a Pd file wires objects together by their
CREATION INDEX (`#X connect 4 0 7 1`), comments included. Inserting one object by
hand silently re-points every connection after it, and nothing complains until
the patch is opened. A generator counts for us.

A DEVICE PATCH IS A TOP-LEVEL CANVAS -- [adc~] in, [dac~] out (ADR-0197).
It is not an abstraction with inlet~/outlet~, and the difference is not
cosmetic: libpd opens a patch as a top-level canvas, where an inlet~ connects
to nothing at all. These three patches USED to be written that way; each
opened, rendered its blocks, and emitted pure silence with no error anywhere
(ADR-0183 d11). [adc~ 1 2] is the main input and the channels after it are a
sidechain key, which is the order LibPdEngine fills its input buffer in.

SUBPATCHES KEEP inlet~/outlet~. A subpatch is part of the same canvas -- it
shares the parent's $0 -- so its inlets are real. Only the TOP level changed.

The DSP maths does not live here. It lives in src/adi/dsp/, where it is tested:
the EQ receives coefficients the host computed with dsp::toPd(), and the limiter
and RMSC mirror dsp::LookaheadLimiter and dsp::RingModSidechain. These patches
are UNRUN on the machine that generated them -- no Pd there -- and are checked
structurally by adi_dsp_tests until libpd lands and they can be compared against
the reference sample for sample.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'pd')


class Patch:
    """One Pd canvas. `obj` returns the new object's index, so a connection is
    made by name, never by counting."""

    def __init__(self, w=900, h=700):
        self.lines = ['#N canvas 0 50 %d %d 12;' % (w, h)]
        self.n = 0

    def _add(self, line):
        self.lines.append(line)
        i = self.n
        self.n += 1
        return i

    def obj(self, x, y, text):
        return self._add('#X obj %d %d %s;' % (x, y, text))

    def msg(self, x, y, text):
        return self._add('#X msg %d %d %s;' % (x, y, text))

    def text(self, x, y, text):
        # A comment IS an object as far as the numbering goes.
        return self._add('#X text %d %d %s;' % (x, y, text))

    def connect(self, a, outlet, b, inlet):
        self.lines.append('#X connect %d %d %d %d;' % (a, outlet, b, inlet))

    def subpatch(self, x, y, name, child):
        """Embed `child` as [pd name]. Inside it the numbering restarts at 0;
        in THIS canvas the whole subpatch is one object, created by the
        restore line -- which is why it is added last. A subpatch shares its
        parent's $0, unlike an abstraction."""
        self.lines.append('#N canvas 0 50 450 300 %s 0;' % name)
        self.lines.extend(child.lines[1:])
        return self._add('#X restore %d %d pd %s;' % (x, y, name))

    def render(self):
        return '\n'.join(self.lines) + '\n'


def pd_comment(s):
    # Pd comments cannot hold bare commas or semicolons.
    return s.replace(',', ' \\,').replace(';', ' \\;')


# ---------------------------------------------------------------------------
# RMSC
# ---------------------------------------------------------------------------

def rmsc():
    """dsp::RingModSidechain. Stereo main, mono key.

    gain = 1 - depth * clip(env, 0, 1), where env is |key|, optionally smoothed.
    Receives: $0-depth (0..1), $0-smooth-on (0 or 1), $0-smooth-hz."""
    p = Patch()
    p.text(20, 10, pd_comment('adi-rmsc -- ring-mod sidechain ducking. ADR-0096. Generated by tools/gen_pd_patches.py: do not edit by hand.'))
    # Channels 1 and 2 are the main input; 3 is the key (ADR-0197). One
    # [adc~ 1 2] with two outlets, not two objects: that is how Pd spells it.
    adc = p.obj(20, 50, 'adc~ 1 2')
    key = p.obj(260, 50, 'adc~ 3')
    rect = p.obj(260, 90, 'abs~')

    # Raw or smoothed: env = raw + (smooth - raw) * on. lop~ at 0 Hz would
    # FREEZE the envelope rather than bypass it, so "off" is a crossfade to
    # the raw rectification, never a zero cutoff.
    lop = p.obj(360, 130, 'lop~ 10')
    rhz = p.obj(460, 90, 'r \\$0-smooth-hz')
    diff = p.obj(360, 170, '-~')
    on = p.obj(360, 210, '*~ 0')
    ron = p.obj(460, 170, 'r \\$0-smooth-on')
    env = p.obj(260, 250, '+~')

    # CLAMPED: a key above full scale must not drive the gain below zero and
    # turn the music upside down.
    clamp = p.obj(260, 290, 'clip~ 0 1')
    depth = p.obj(260, 330, '*~ 1')
    rdep = p.obj(360, 290, 'r \\$0-depth')
    gain = p.obj(260, 370, 'expr~ 1 - $v1')
    mulL = p.obj(20, 420, '*~')
    mulR = p.obj(120, 420, '*~')
    dac = p.obj(20, 460, 'dac~ 1 2')

    p.connect(key, 0, rect, 0)
    p.connect(rect, 0, lop, 0)
    p.connect(rhz, 0, lop, 1)
    p.connect(lop, 0, diff, 0)
    p.connect(rect, 0, diff, 1)
    p.connect(diff, 0, on, 0)
    p.connect(ron, 0, on, 1)
    p.connect(rect, 0, env, 0)
    p.connect(on, 0, env, 1)
    p.connect(env, 0, clamp, 0)
    p.connect(clamp, 0, depth, 0)
    p.connect(rdep, 0, depth, 1)
    p.connect(depth, 0, gain, 0)
    p.connect(adc, 0, mulL, 0)
    p.connect(adc, 1, mulR, 0)
    p.connect(gain, 0, mulL, 1)
    p.connect(gain, 0, mulR, 1)
    p.connect(mulL, 0, dac, 0)
    p.connect(mulR, 0, dac, 1)
    return p.render()


# ---------------------------------------------------------------------------
# The limiter
# ---------------------------------------------------------------------------

def limiter():
    """The Pd limiter: SAMPLE PEAK, lookahead, and the ADR-0095 latency protocol.

    Vanilla Pd has no sliding-window minimum, so this cannot reproduce
    dsp::LookaheadLimiter's exact guarantee. It uses an instant-attack,
    exponential-release PEAK follower on the undelayed signal -- never env~,
    which is RMS -- and a final clip~ at the ceiling for the residual that the
    release can leave, which is bounded by the release over the lookahead.

    Receives: $0-lookahead-ms (1.5, 3 or 6), $0-ceiling (linear),
              $0-release (coefficient per sample), $0-query_latency (bang).
    Sends:    $0-report_latency (samples).
    """
    p = Patch(1100, 800)
    p.text(20, 10, pd_comment('adi-limiter -- lookahead brickwall on SAMPLE PEAK. ADR-0095 and ADR-0096. Generated: do not edit by hand.'))
    adc = p.obj(20, 50, 'adc~ 1 2')

    # --- detection: peak of both channels, instant attack, exponential release
    aL = p.obj(20, 100, 'abs~')
    aR = p.obj(160, 100, 'abs~')
    both = p.obj(20, 140, 'max~')
    follow = p.obj(20, 180, 'fexpr~ max($x1[0] \\, $y1[-1] * $f2)')
    rrel = p.obj(300, 140, 'r \\$0-release')
    gainx = p.obj(20, 220, 'expr~ min(1 \\, $f2 / max($v1 \\, 1e-9))')
    rceil = p.obj(300, 180, 'r \\$0-ceiling')

    # --- latency: whole samples, reported and used ------------------------
    # samples = round(ms * sr / 1000), sent to $0-report_latency (ADR-0095),
    # and turned back into ms for delread~ so the delay IS that whole number.
    #
    # [t b b], NOT A FAN-OUT. A query must read the sample rate BEFORE it
    # computes the report, and Pd does not promise the order of a fan-out --
    # the first version of this patch fanned out, which can report at the old
    # rate: the exact bug ADR-0095 decision 2 exists to prevent. A trigger
    # fires right to left, always.
    rms = p.obj(560, 50, 'r \\$0-lookahead-ms')
    rquery = p.obj(760, 50, 'r \\$0-query_latency')
    lb = p.obj(940, 50, 'loadbang')
    trig = p.obj(760, 90, 't b b')
    keep = p.obj(560, 130, 'f 1.5')
    sr = p.obj(860, 130, 'samplerate~')
    # samplerate~ feeds the COLD inlets directly. The first version parked it
    # in an [f] that nothing ever banged, so the expr always saw a rate of 0
    # and the patch reported zero latency -- forever, and silently.
    tosamples = p.obj(560, 180, 'expr int($f1 * $f2 / 1000 + 0.5)')
    report = p.obj(560, 220, 's \\$0-report_latency')
    toms = p.obj(760, 220, 'expr $f1 * 1000 / $f2')

    # --- the lookahead delay, write sorted BEFORE read ---------------------
    # Separate subpatches, and the writer's dummy outlet~ wired into the
    # reader's dummy inlet~: that connection is what makes Pd's DSP sort run
    # the writer first. Left to themselves in one canvas, a reader sorted
    # first reads a whole block late, and the reported latency is wrong by a
    # block -- which compensates every other track wrongly.
    w = Patch()
    wl = w.obj(20, 20, 'inlet~')
    wr = w.obj(150, 20, 'inlet~')
    dwl = w.obj(20, 60, 'delwrite~ \\$0-laL 50')
    dwr = w.obj(150, 60, 'delwrite~ \\$0-laR 50')
    w.obj(20, 110, 'outlet~')                      # the sort dependency, nothing more
    w.connect(wl, 0, dwl, 0)
    w.connect(wr, 0, dwr, 0)
    write = p.subpatch(20, 300, 'write', w)

    r = Patch()
    r.obj(20, 20, 'inlet~')                        # inlet 0: the sort dependency
    rms_in = r.obj(150, 20, 'inlet')               # inlet 1: delay in ms
    drl = r.obj(20, 60, 'delread~ \\$0-laL')
    drr = r.obj(150, 60, 'delread~ \\$0-laR')
    ol = r.obj(20, 110, 'outlet~')
    orr = r.obj(150, 110, 'outlet~')
    r.connect(rms_in, 0, drl, 0)
    r.connect(rms_in, 0, drr, 0)
    r.connect(drl, 0, ol, 0)
    r.connect(drr, 0, orr, 0)
    read = p.subpatch(20, 360, 'read', r)

    mulL = p.obj(20, 420, '*~')
    mulR = p.obj(160, 420, '*~')
    # The safety net. It only ever touches the residual the release leaves.
    clipL = p.obj(20, 460, 'clip~ -1 1')
    clipR = p.obj(160, 460, 'clip~ -1 1')
    ceilClip = p.obj(300, 420, 'r \\$0-ceiling')
    neg = p.obj(300, 460, 'expr -$f1')
    dac = p.obj(20, 510, 'dac~ 1 2')

    p.connect(adc, 0, aL, 0)
    p.connect(adc, 1, aR, 0)
    p.connect(aL, 0, both, 0)
    p.connect(aR, 0, both, 1)
    p.connect(both, 0, follow, 0)
    p.connect(rrel, 0, follow, 1)
    p.connect(follow, 0, gainx, 0)
    p.connect(rceil, 0, gainx, 1)

    p.connect(rms, 0, keep, 0)
    p.connect(rquery, 0, trig, 0)
    p.connect(lb, 0, trig, 0)
    p.connect(trig, 1, sr, 0)          # right outlet first: the rate...
    p.connect(trig, 0, keep, 0)        # ...then the report
    p.connect(sr, 0, tosamples, 1)
    p.connect(sr, 0, toms, 1)
    p.connect(keep, 0, tosamples, 0)
    p.connect(tosamples, 0, report, 0)
    p.connect(tosamples, 0, toms, 0)

    p.connect(adc, 0, write, 0)
    p.connect(adc, 1, write, 1)
    p.connect(write, 0, read, 0)       # the dependency that orders the sort
    p.connect(toms, 0, read, 1)
    p.connect(read, 0, mulL, 0)
    p.connect(read, 1, mulR, 0)
    p.connect(gainx, 0, mulL, 1)
    p.connect(gainx, 0, mulR, 1)
    p.connect(mulL, 0, clipL, 0)
    p.connect(mulR, 0, clipR, 0)
    p.connect(ceilClip, 0, clipL, 2)
    p.connect(ceilClip, 0, clipR, 2)
    p.connect(ceilClip, 0, neg, 0)
    p.connect(neg, 0, clipL, 1)
    p.connect(neg, 0, clipR, 1)
    p.connect(clipL, 0, dac, 0)
    p.connect(clipR, 0, dac, 1)
    return p.render()


# ---------------------------------------------------------------------------
# The eight-band EQ
# ---------------------------------------------------------------------------

BANDS = 8
SECTIONS = 4     # a 48 dB/oct cut is four Butterworth sections (ADR-0096)


def eq8():
    """Eight bands, four biquad~ sections each, per channel.

    NO COEFFICIENT MATHS IN THE PATCH. Each section listens on $0-b<band>-s<k>
    for the five numbers `biquad~` takes, which the host computes with
    dsp::peaking / lowShelf / highShelf / cut, converts with dsp::toPd -- the
    sign flip -- and formats with dsp::pdMessage. A bell or shelf uses section 1
    and sends the pass-through `0 0 1 0 0` to the other three; a 48 dB/oct cut
    uses all four with staggered Q."""
    p = Patch(1400, 900)
    p.text(20, 10, pd_comment('adi-eq8 -- 8 bands x 4 biquad~ sections per channel. Coefficients come from the host via dsp::toPd -- never computed here. ADR-0096. Generated: do not edit by hand.'))
    adc = p.obj(20, 50, 'adc~ 1 2')
    prevL, prevR = (adc, 0), (adc, 1)
    y = 90
    for b in range(1, BANDS + 1):
        for k in range(1, SECTIONS + 1):
            rcv = p.obj(360, y, 'r \\$0-b%d-s%d' % (b, k))
            bqL = p.obj(20, y, 'biquad~ 0 0 1 0 0')
            bqR = p.obj(700, y, 'biquad~ 0 0 1 0 0')
            # (object, outlet), because the head of the chain is now one
            # [adc~ 1 2] with two outlets rather than two separate objects.
            p.connect(prevL[0], prevL[1], bqL, 0)
            p.connect(prevR[0], prevR[1], bqR, 0)
            p.connect(rcv, 0, bqL, 0)
            p.connect(rcv, 0, bqR, 0)
            prevL, prevR = (bqL, 0), (bqR, 0)
            y += 24
    dac = p.obj(20, y + 20, 'dac~ 1 2')
    p.connect(prevL[0], prevL[1], dac, 0)
    p.connect(prevR[0], prevR[1], dac, 1)
    return p.render()


# ---------------------------------------------------------------------------
# The analyser
# ---------------------------------------------------------------------------

# THESE FOUR NUMBERS ARE ALSO IN src/adi/dsp/spectrum.hpp, and nothing at run
# time keeps them equal -- a Pd patch is a file, not a caller. What keeps them
# equal is a test: adi_pd_engine_tests reads the window this patch builds,
# compares it with dsp::fillWindow sample for sample, and sends one sine
# through both paths expecting 0.00 dBFS from each (ADR-0183 d7). Change one
# side and that test fails; change neither and a producer sees one curve.
FFT_SIZE = 1024
OVERLAP = 4
BINS = FFT_SIZE // 2 + 1
PUBLISH_HZ = 30
FLOOR_DB = -120


def spectrum():
    """The analyser's DSP tier: one calibrated dBFS spectrum in an [adi.array].

    A TOP-LEVEL CANVAS (ADR-0197): [adc~ 1 2] in, and no [dac~] -- an analyser
    hears and does not speak. That is not an oversight; ADR-0183's first line is
    that this device never touches the audio, and the surest way to keep that
    true is to give the patch nothing to write to.
    """
    p = Patch(1000, 760)
    p.text(20, 10, pd_comment(
        'adi-spectrum -- the analyser DSP tier (ADR-0183, ADR-0195 d5). '
        'Generated: do not edit by hand.'))
    p.text(20, 40, pd_comment(
        'NO dac~. An analyser hears and does not speak (ADR-0183): the patch '
        'has nothing to write to, so it cannot touch the audio even by mistake.'))

    adc = p.obj(20, 90, 'adc~ 1 2')
    # MONO SUM, and halved. A spectrum of the stereo pair is one picture, and
    # summing without the half would read +6 dB on anything centred -- which is
    # most of a mix.
    sum_ = p.obj(20, 140, '+~')
    half = p.obj(20, 180, '*~ 0.5')

    # The window table. `cosinesum <n> 0.5 -0.5` is 0.5 - 0.5cos(2pi i / n):
    # Pd's phase increment is 2*pi/npoints, so it is PERIODIC, which is the same
    # convention dsp::fillWindow uses. Checked in g_array.c rather than assumed.
    #
    # It resizes the array to n + 3 -- Pd keeps three interpolation guard points
    # -- so the table is 1027 long and [tabreceive~] reads the first 1024. That
    # is not an off-by-three.
    #
    # The message goes through [s], because $0 DOES NOT EXPAND IN A MESSAGE BOX
    # (ADR-0183 d15): a message beginning "; $0-window ..." would address a
    # receiver literally called "0-window".
    p.text(520, 90, pd_comment(
        'The window, built once at load. cosinesum is periodic (2pi/n), which '
        'is what dsp::fillWindow does; it resizes to n+3 for Pd\'s guard points.'))
    arr = p.obj(520, 150, 'table \$0-window %d' % FFT_SIZE)
    lb = p.obj(520, 190, 'loadbang')
    msg = p.msg(520, 230, 'cosinesum %d 0.5 -0.5' % FFT_SIZE)
    swin = p.obj(520, 270, 's \$0-window')
    p.connect(lb, 0, msg, 0)
    p.connect(msg, 0, swin, 0)

    # The declaration. min/max/unit are ADR-0177 fix 2 applied: a renderer given
    # only a length and a rate would have to guess that these are decibels and
    # where the floor is, and a guess about a dB floor draws a picture that is
    # wrong in a way nobody can see.
    p.obj(520, 330, 'adi.array \$0 1 %d %d %d 0 dB Spectrum'
          % (BINS, PUBLISH_HZ, FLOOR_DB))

    # --- the analysis, in its own block ------------------------------------
    a = Patch()
    a.obj(20, 20, 'block~ %d %d' % (FFT_SIZE, OVERLAP))
    ain = a.obj(20, 60, 'inlet~')
    win = a.obj(160, 60, 'tabreceive~ \$0-window')
    wm = a.obj(20, 100, '*~')
    fft = a.obj(20, 140, 'rfft~')
    # CALIBRATED dBFS IN ONE EXPRESSION. 2/sum(w) is the coherent-gain
    # correction, and for a periodic Hann of N points sum(w) is exactly N/2, so
    # the constant is 4/N. A full-scale sine then reads 0.00 (ADR-0183 d7).
    # max() keeps log10 away from zero, which every silent bin is.
    #
    # THE COMMA IS ESCAPED, and it has to be. In a Pd FILE a comma separates
    # messages, so `max(x, y)` written plainly ends the object box at the
    # comma: Pd reports "an open parenthesis not matched", the expr~ never
    # creates, the patch opens anyway, and the array stays at zero. Exactly the
    # shape of ADR-0183 d11 -- valid file, silent result, nothing that fails.
    # Found by the console hook, after a test that could not fail was made to.
    #
    # The floor is written out rather than as 1e-9: Pd's expr lexes its own
    # numbers, and the Max build's `expr` did not take exponent notation at all
    # (adi-m4l-analyzer/PROJECT.md). Nine zeros cost nothing and ask no
    # questions.
    mag = a.obj(20, 190,
                'expr~ 20*log10(max(sqrt($v1*$v1 + $v2*$v2) * %.10g \\, 0.000000001))'
                % (4.0 / FFT_SIZE))
    # Clamped to the range the declaration promises: a renderer told the floor
    # is -120 should never be handed -180.
    clamp = a.obj(20, 240, 'clip~ %d 0' % FLOOR_DB)
    bang = a.obj(300, 190, 'bang~')
    tab = a.obj(20, 290, 'tabwrite~ \$0-adiarr-1')
    a.connect(ain, 0, wm, 0)
    a.connect(win, 0, wm, 1)
    a.connect(wm, 0, fft, 0)
    a.connect(fft, 0, mag, 0)
    a.connect(fft, 1, mag, 1)
    a.connect(mag, 0, clamp, 0)
    a.connect(clamp, 0, tab, 0)
    # One bang per block writes the frame. [tabwrite~] takes the first `bins`
    # samples of the block, which are exactly the bins rfft~ fills; the rest of
    # a real transform's output is the mirror nobody plots.
    a.connect(bang, 0, tab, 0)
    analysis = p.subpatch(20, 240, 'analysis', a)

    p.connect(adc, 0, sum_, 0)
    p.connect(adc, 1, sum_, 1)
    p.connect(sum_, 0, half, 0)
    p.connect(half, 0, analysis, 0)
    return p.render()


PATCHES = {
    'adi-rmsc.pd': rmsc,
    'adi-limiter.pd': limiter,
    'adi-eq8.pd': eq8,
    'adi-spectrum.pd': spectrum,
}


def main():
    check = '--check' in sys.argv
    os.makedirs(OUT, exist_ok=True)
    stale = []
    for name, make in PATCHES.items():
        text = make()
        path = os.path.join(OUT, name)
        if check:
            try:
                with open(path, encoding='utf-8', newline='') as f:
                    # CRLF-tolerant, as validate_pd.py is: Git on Windows
                    # checks these out with CRLF.
                    if f.read().replace('\r\n', '\n') != text:
                        stale.append(name)
            except FileNotFoundError:
                stale.append(name)
        else:
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            print('wrote', os.path.relpath(path))
    if check:
        if stale:
            print('stale Pd patches (run tools/gen_pd_patches.py):', ', '.join(stale))
            return 1
        print('Pd patches are up to date')
    return 0


if __name__ == '__main__':
    sys.exit(main())
