#!/usr/bin/env python3
"""Generate adi_daw's Pd modules -- ADR-0096.

    python adi_daw/tools/gen_pd_patches.py            write adi_daw/pd/*.pd
    python adi_daw/tools/gen_pd_patches.py --check    exit 1 if they are stale

Generated, not hand-written, because a Pd file wires objects together by their
CREATION INDEX (`#X connect 4 0 7 1`), comments included. Inserting one object by
hand silently re-points every connection after it, and nothing complains until
the patch is opened. A generator counts for us.

The DSP maths does not live here. It lives in src/adi/dsp/, where it is tested:
the EQ receives coefficients the host computed with dsp::toPd(), and the limiter
and RMSC mirror dsp::LookaheadLimiter and dsp::RingModSidechain. These patches
are UNRUN on the machine that generated them -- no Pd there -- and are checked
structurally by adi_dsp_tests until libpd lands and they can be compared against
the reference sample for sample.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'pd')


class Patch:
    """One Pd canvas. `obj` returns the new object's index, so a connection is
    made by name, never by counting."""

    def __init__(self, w=900, h=700):
        self.lines = ['#N canvas 0 50 %d %d 12;' % (w, h)]
        self.n = 0

    def _add(self, line):
        self.lines.append(line)
        i = self.n
        self.n += 1
        return i

    def obj(self, x, y, text):
        return self._add('#X obj %d %d %s;' % (x, y, text))

    def msg(self, x, y, text):
        return self._add('#X msg %d %d %s;' % (x, y, text))

    def text(self, x, y, text):
        # A comment IS an object as far as the numbering goes.
        return self._add('#X text %d %d %s;' % (x, y, text))

    def connect(self, a, outlet, b, inlet):
        self.lines.append('#X connect %d %d %d %d;' % (a, outlet, b, inlet))

    def subpatch(self, x, y, name, child):
        """Embed `child` as [pd name]. Inside it the numbering restarts at 0;
        in THIS canvas the whole subpatch is one object, created by the
        restore line -- which is why it is added last. A subpatch shares its
        parent's $0, unlike an abstraction."""
        self.lines.append('#N canvas 0 50 450 300 %s 0;' % name)
        self.lines.extend(child.lines[1:])
        return self._add('#X restore %d %d pd %s;' % (x, y, name))

    def render(self):
        return '\n'.join(self.lines) + '\n'


def pd_comment(s):
    # Pd comments cannot hold bare commas or semicolons.
    return s.replace(',', ' \\,').replace(';', ' \\;')


# ---------------------------------------------------------------------------
# RMSC
# ---------------------------------------------------------------------------

def rmsc():
    """dsp::RingModSidechain. Stereo main, mono key.

    gain = 1 - depth * clip(env, 0, 1), where env is |key|, optionally smoothed.
    Receives: $0-depth (0..1), $0-smooth-on (0 or 1), $0-smooth-hz."""
    p = Patch()
    p.text(20, 10, pd_comment('adi-rmsc -- ring-mod sidechain ducking. ADR-0096. Generated by tools/gen_pd_patches.py: do not edit by hand.'))
    inL = p.obj(20, 50, 'inlet~')
    inR = p.obj(120, 50, 'inlet~')
    key = p.obj(260, 50, 'inlet~')
    rect = p.obj(260, 90, 'abs~')

    # Raw or smoothed: env = raw + (smooth - raw) * on. lop~ at 0 Hz would
    # FREEZE the envelope rather than bypass it, so "off" is a crossfade to
    # the raw rectification, never a zero cutoff.
    lop = p.obj(360, 130, 'lop~ 10')
    rhz = p.obj(460, 90, 'r \\$0-smooth-hz')
    diff = p.obj(360, 170, '-~')
    on = p.obj(360, 210, '*~ 0')
    ron = p.obj(460, 170, 'r \\$0-smooth-on')
    env = p.obj(260, 250, '+~')

    # CLAMPED: a key above full scale must not drive the gain below zero and
    # turn the music upside down.
    clamp = p.obj(260, 290, 'clip~ 0 1')
    depth = p.obj(260, 330, '*~ 1')
    rdep = p.obj(360, 290, 'r \\$0-depth')
    gain = p.obj(260, 370, 'expr~ 1 - $v1')
    mulL = p.obj(20, 420, '*~')
    mulR = p.obj(120, 420, '*~')
    outL = p.obj(20, 460, 'outlet~')
    outR = p.obj(120, 460, 'outlet~')

    p.connect(key, 0, rect, 0)
    p.connect(rect, 0, lop, 0)
    p.connect(rhz, 0, lop, 1)
    p.connect(lop, 0, diff, 0)
    p.connect(rect, 0, diff, 1)
    p.connect(diff, 0, on, 0)
    p.connect(ron, 0, on, 1)
    p.connect(rect, 0, env, 0)
    p.connect(on, 0, env, 1)
    p.connect(env, 0, clamp, 0)
    p.connect(clamp, 0, depth, 0)
    p.connect(rdep, 0, depth, 1)
    p.connect(depth, 0, gain, 0)
    p.connect(inL, 0, mulL, 0)
    p.connect(inR, 0, mulR, 0)
    p.connect(gain, 0, mulL, 1)
    p.connect(gain, 0, mulR, 1)
    p.connect(mulL, 0, outL, 0)
    p.connect(mulR, 0, outR, 0)
    return p.render()


# ---------------------------------------------------------------------------
# The limiter
# ---------------------------------------------------------------------------

def limiter():
    """The Pd limiter: SAMPLE PEAK, lookahead, and the ADR-0095 latency protocol.

    Vanilla Pd has no sliding-window minimum, so this cannot reproduce
    dsp::LookaheadLimiter's exact guarantee. It uses an instant-attack,
    exponential-release PEAK follower on the undelayed signal -- never env~,
    which is RMS -- and a final clip~ at the ceiling for the residual that the
    release can leave, which is bounded by the release over the lookahead.

    Receives: $0-lookahead-ms (1.5, 3 or 6), $0-ceiling (linear),
              $0-release (coefficient per sample), $0-query_latency (bang).
    Sends:    $0-report_latency (samples).
    """
    p = Patch(1100, 800)
    p.text(20, 10, pd_comment('adi-limiter -- lookahead brickwall on SAMPLE PEAK. ADR-0095 and ADR-0096. Generated: do not edit by hand.'))
    inL = p.obj(20, 50, 'inlet~')
    inR = p.obj(160, 50, 'inlet~')

    # --- detection: peak of both channels, instant attack, exponential release
    aL = p.obj(20, 100, 'abs~')
    aR = p.obj(160, 100, 'abs~')
    both = p.obj(20, 140, 'max~')
    follow = p.obj(20, 180, 'fexpr~ max($x1[0] \\, $y1[-1] * $f2)')
    rrel = p.obj(300, 140, 'r \\$0-release')
    gainx = p.obj(20, 220, 'expr~ min(1 \\, $f2 / max($v1 \\, 1e-9))')
    rceil = p.obj(300, 180, 'r \\$0-ceiling')

    # --- latency: whole samples, reported and used ------------------------
    # samples = round(ms * sr / 1000), sent to $0-report_latency (ADR-0095),
    # and turned back into ms for delread~ so the delay IS that whole number.
    #
    # [t b b], NOT A FAN-OUT. A query must read the sample rate BEFORE it
    # computes the report, and Pd does not promise the order of a fan-out --
    # the first version of this patch fanned out, which can report at the old
    # rate: the exact bug ADR-0095 decision 2 exists to prevent. A trigger
    # fires right to left, always.
    rms = p.obj(560, 50, 'r \\$0-lookahead-ms')
    rquery = p.obj(760, 50, 'r \\$0-query_latency')
    lb = p.obj(940, 50, 'loadbang')
    trig = p.obj(760, 90, 't b b')
    keep = p.obj(560, 130, 'f 1.5')
    sr = p.obj(860, 130, 'samplerate~')
    # samplerate~ feeds the COLD inlets directly. The first version parked it
    # in an [f] that nothing ever banged, so the expr always saw a rate of 0
    # and the patch reported zero latency -- forever, and silently.
    tosamples = p.obj(560, 180, 'expr int($f1 * $f2 / 1000 + 0.5)')
    report = p.obj(560, 220, 's \\$0-report_latency')
    toms = p.obj(760, 220, 'expr $f1 * 1000 / $f2')

    # --- the lookahead delay, write sorted BEFORE read ---------------------
    # Separate subpatches, and the writer's dummy outlet~ wired into the
    # reader's dummy inlet~: that connection is what makes Pd's DSP sort run
    # the writer first. Left to themselves in one canvas, a reader sorted
    # first reads a whole block late, and the reported latency is wrong by a
    # block -- which compensates every other track wrongly.
    w = Patch()
    wl = w.obj(20, 20, 'inlet~')
    wr = w.obj(150, 20, 'inlet~')
    dwl = w.obj(20, 60, 'delwrite~ \\$0-laL 50')
    dwr = w.obj(150, 60, 'delwrite~ \\$0-laR 50')
    w.obj(20, 110, 'outlet~')                      # the sort dependency, nothing more
    w.connect(wl, 0, dwl, 0)
    w.connect(wr, 0, dwr, 0)
    write = p.subpatch(20, 300, 'write', w)

    r = Patch()
    r.obj(20, 20, 'inlet~')                        # inlet 0: the sort dependency
    rms_in = r.obj(150, 20, 'inlet')               # inlet 1: delay in ms
    drl = r.obj(20, 60, 'delread~ \\$0-laL')
    drr = r.obj(150, 60, 'delread~ \\$0-laR')
    ol = r.obj(20, 110, 'outlet~')
    orr = r.obj(150, 110, 'outlet~')
    r.connect(rms_in, 0, drl, 0)
    r.connect(rms_in, 0, drr, 0)
    r.connect(drl, 0, ol, 0)
    r.connect(drr, 0, orr, 0)
    read = p.subpatch(20, 360, 'read', r)

    mulL = p.obj(20, 420, '*~')
    mulR = p.obj(160, 420, '*~')
    # The safety net. It only ever touches the residual the release leaves.
    clipL = p.obj(20, 460, 'clip~ -1 1')
    clipR = p.obj(160, 460, 'clip~ -1 1')
    ceilClip = p.obj(300, 420, 'r \\$0-ceiling')
    neg = p.obj(300, 460, 'expr -$f1')
    outL = p.obj(20, 510, 'outlet~')
    outR = p.obj(160, 510, 'outlet~')

    p.connect(inL, 0, aL, 0)
    p.connect(inR, 0, aR, 0)
    p.connect(aL, 0, both, 0)
    p.connect(aR, 0, both, 1)
    p.connect(both, 0, follow, 0)
    p.connect(rrel, 0, follow, 1)
    p.connect(follow, 0, gainx, 0)
    p.connect(rceil, 0, gainx, 1)

    p.connect(rms, 0, keep, 0)
    p.connect(rquery, 0, trig, 0)
    p.connect(lb, 0, trig, 0)
    p.connect(trig, 1, sr, 0)          # right outlet first: the rate...
    p.connect(trig, 0, keep, 0)        # ...then the report
    p.connect(sr, 0, tosamples, 1)
    p.connect(sr, 0, toms, 1)
    p.connect(keep, 0, tosamples, 0)
    p.connect(tosamples, 0, report, 0)
    p.connect(tosamples, 0, toms, 0)

    p.connect(inL, 0, write, 0)
    p.connect(inR, 0, write, 1)
    p.connect(write, 0, read, 0)       # the dependency that orders the sort
    p.connect(toms, 0, read, 1)
    p.connect(read, 0, mulL, 0)
    p.connect(read, 1, mulR, 0)
    p.connect(gainx, 0, mulL, 1)
    p.connect(gainx, 0, mulR, 1)
    p.connect(mulL, 0, clipL, 0)
    p.connect(mulR, 0, clipR, 0)
    p.connect(ceilClip, 0, clipL, 2)
    p.connect(ceilClip, 0, clipR, 2)
    p.connect(ceilClip, 0, neg, 0)
    p.connect(neg, 0, clipL, 1)
    p.connect(neg, 0, clipR, 1)
    p.connect(clipL, 0, outL, 0)
    p.connect(clipR, 0, outR, 0)
    return p.render()


# ---------------------------------------------------------------------------
# The eight-band EQ
# ---------------------------------------------------------------------------

BANDS = 8
SECTIONS = 4     # a 48 dB/oct cut is four Butterworth sections (ADR-0096)


def eq8():
    """Eight bands, four biquad~ sections each, per channel.

    NO COEFFICIENT MATHS IN THE PATCH. Each section listens on $0-b<band>-s<k>
    for the five numbers `biquad~` takes, which the host computes with
    dsp::peaking / lowShelf / highShelf / cut, converts with dsp::toPd -- the
    sign flip -- and formats with dsp::pdMessage. A bell or shelf uses section 1
    and sends the pass-through `0 0 1 0 0` to the other three; a 48 dB/oct cut
    uses all four with staggered Q."""
    p = Patch(1400, 900)
    p.text(20, 10, pd_comment('adi-eq8 -- 8 bands x 4 biquad~ sections per channel. Coefficients come from the host via dsp::toPd -- never computed here. ADR-0096. Generated: do not edit by hand.'))
    inL = p.obj(20, 50, 'inlet~')
    inR = p.obj(700, 50, 'inlet~')
    prevL, prevR = inL, inR
    y = 90
    for b in range(1, BANDS + 1):
        for k in range(1, SECTIONS + 1):
            rcv = p.obj(360, y, 'r \\$0-b%d-s%d' % (b, k))
            bqL = p.obj(20, y, 'biquad~ 0 0 1 0 0')
            bqR = p.obj(700, y, 'biquad~ 0 0 1 0 0')
            p.connect(prevL, 0, bqL, 0)
            p.connect(prevR, 0, bqR, 0)
            p.connect(rcv, 0, bqL, 0)
            p.connect(rcv, 0, bqR, 0)
            prevL, prevR = bqL, bqR
            y += 24
    outL = p.obj(20, y + 20, 'outlet~')
    outR = p.obj(700, y + 20, 'outlet~')
    p.connect(prevL, 0, outL, 0)
    p.connect(prevR, 0, outR, 0)
    return p.render()


PATCHES = {
    'adi-rmsc.pd': rmsc,
    'adi-limiter.pd': limiter,
    'adi-eq8.pd': eq8,
}


def main():
    check = '--check' in sys.argv
    os.makedirs(OUT, exist_ok=True)
    stale = []
    for name, make in PATCHES.items():
        text = make()
        path = os.path.join(OUT, name)
        if check:
            try:
                with open(path, encoding='utf-8', newline='') as f:
                    # CRLF-tolerant, as validate_pd.py is: Git on Windows
                    # checks these out with CRLF.
                    if f.read().replace('\r\n', '\n') != text:
                        stale.append(name)
            except FileNotFoundError:
                stale.append(name)
        else:
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            print('wrote', os.path.relpath(path))
    if check:
        if stale:
            print('stale Pd patches (run tools/gen_pd_patches.py):', ', '.join(stale))
            return 1
        print('Pd patches are up to date')
    return 0


if __name__ == '__main__':
    sys.exit(main())
