#!/usr/bin/env python3
"""Check the committed Pd patches are what their generator produces -- ADR-0096.

    python3 adi_daw/tools/validate_pd.py

The patches in adi_daw/pd/ are generated by tools/gen_pd_patches.py, because a
Pd file wires objects by creation index and a hand edit silently re-points every
connection after it. That only protects anything if nobody edits the generator
and forgets to regenerate -- this is the check that notices.

Found by test_all.sh and by CI through their `validate_*.py` glob, so it needs
no registration anywhere.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import gen_pd_patches  # noqa: E402


def main():
    stale = []
    for name, make in gen_pd_patches.PATCHES.items():
        path = os.path.join(gen_pd_patches.OUT, name)
        try:
            with open(path, encoding='utf-8', newline='') as f:
                on_disk = f.read()
        except FileNotFoundError:
            stale.append(name + ' (missing)')
            continue
        # LINE ENDINGS NORMALISED. Git on Windows checks these out with CRLF,
        # and a byte-for-byte comparison would call every fresh checkout stale.
        if on_disk.replace('\r\n', '\n') != make():
            stale.append(name)
    if stale:
        print('stale Pd patches -- run: python adi_daw/tools/gen_pd_patches.py')
        for s in stale:
            print('  ' + s)
        return 1
    print('ok    %d Pd patches match their generator' % len(gen_pd_patches.PATCHES))
    return 0


if __name__ == '__main__':
    sys.exit(main())
