// Generated by the build script — embedded fallback so the app works offline
// and before the first push. users mirrors users.json; workspaces holds seed lists.
window.RQC_SEED = {
  "users": {
    "version": 2,
    "kdf": {
      "algo": "PBKDF2-SHA256",
      "iterations": 150000,
      "bytes": 32
    },
    "users": [
      {
        "id": "public",
        "label": "Public",
        "salt": null,
        "hash": null,
        "deleteSalt": "pIuTbZ/DoSoFPnyjMTcuhQ==",
        "deleteHash": "j443bsn28n4vf6mNjNW5700nnxO1d5XPDSlvJffimis="
      },
      {
        "id": "avastha",
        "label": "Avastha",
        "salt": "2Km9z/RETvsYXAV2Tw9k4A==",
        "hash": "YdQb8bApSISq5WWRZrKB5/fy/SHOIJtdr7Y02QGomZA="
      },
      {
        "id": "adi",
        "label": "Adi",
        "salt": "YE9hU3Dp3MJ74uXLFs9U6w==",
        "hash": "CsZBNY4QfiN9QkLzX5p9HUVyzb8KZiUzSmYkvC7cxSI="
      },
      {
        "id": "valentin",
        "label": "Valentin",
        "salt": "EYNYyd1jNai91KJJJcDXMw==",
        "hash": "qf0PksZThBH5p19+4IzcdRZOJhnNgafe4GyjvL6ntY4="
      }
    ]
  },
  "workspaces": {
    "avastha": {
      "avastha-4h-set.json": {
        "version": 2,
        "name": "Avastha 4h set",
        "created": "2026-07-11",
        "updated": "2026-07-11",
        "tracks": [
          {
            "title": "F# 110 BPM fast version 140",
            "cueIn": "0",
            "cueOut": "5.18"
          },
          {
            "title": "Ace Ventura, Protonica Nova (Original Mix)",
            "cueIn": "0.54",
            "cueOut": "6.53"
          },
          {
            "title": "Ace Ventura, Volcano S1Mulat1On Nat1On (Original Mix)",
            "cueIn": "1.22",
            "cueOut": "5.15"
          },
          {
            "title": "In Your Thought 2.10.2021 - Complete WAV Mas",
            "cueIn": "0.41",
            "cueOut": "8.27"
          },
          {
            "title": "Avastha - Oscilation Master Fix 22.5.26 v3",
            "cueIn": "0.27",
            "cueOut": "6.1"
          },
          {
            "title": "Lifeforms Ahead of Us (Original Mix)",
            "cueIn": "1.04",
            "cueOut": "7.19"
          },
          {
            "title": "Acid Punks Synergy (Original mix)",
            "cueIn": "0.4",
            "cueOut": "7.53"
          },
          {
            "title": "143BPM Antinomy & Asgard - Tree of Souls (Adi Edit)",
            "cueIn": "0",
            "cueOut": "3.51"
          },
          {
            "title": "Blazy Dystopia",
            "cueIn": "0.46",
            "cueOut": "3.54"
          },
          {
            "title": "Transforming triplet rise with melody13",
            "cueIn": "0",
            "cueOut": "5.28"
          },
          {
            "title": "DMT And Signals-v6 2025-1",
            "cueIn": "1.07",
            "cueOut": "9.5"
          },
          {
            "title": "Spinal Fusion, Starlab (IN), Kamya The Great Awakening Feat. Kamya (Original Mix)",
            "cueIn": "0.26",
            "cueOut": "6.02"
          },
          {
            "title": "E Minor 143 BPM (E, F#, G, A, B, C, D) 458 Premaster WAV",
            "cueIn": "0.26",
            "cueOut": "9.23"
          },
          {
            "title": "Man With No Name Possessed (Acid Punks remix)",
            "cueIn": "0.53",
            "cueOut": "8.57"
          },
          {
            "title": "The Good, The Bad & The Ugly Mescalito (Imagine Mars Remix)",
            "cueIn": "0.39",
            "cueOut": "5.26"
          },
          {
            "title": "AvasthA Kick B Phrygy 144 BPM B C D E F# G-2",
            "cueIn": "0.15",
            "cueOut": "6.34"
          },
          {
            "title": "Trippin B Major 144 BPM (B C# D# E F# G# A#) 450",
            "cueIn": "0.39",
            "cueOut": "6.19"
          },
          {
            "title": "G MinoR 144 BPM 119 APC-1",
            "cueIn": "0.26",
            "cueOut": "7"
          },
          {
            "title": "Amstex Spirit (Original Mix)",
            "cueIn": "0.52",
            "cueOut": "7.5"
          },
          {
            "title": "Outsiders & Mind Spin - Agents Of Time v2 16Bit Master 25-12-2025",
            "cueIn": "0.34",
            "cueOut": "8.04"
          },
          {
            "title": "Drop Of BLS A minor 145 BPM 197",
            "cueIn": "0",
            "cueOut": "7.56"
          },
          {
            "title": "Major Experience F Major 145 (F, G, A, A#, C, D, E)  208",
            "cueIn": "1.19",
            "cueOut": "7.35"
          },
          {
            "title": "Avastha - The Right Choice",
            "cueIn": "0.26",
            "cueOut": "5.57"
          },
          {
            "title": "Life Experiences",
            "cueIn": "0.26",
            "cueOut": "6.57"
          },
          {
            "title": "Kick G# Major 145 BPM 401",
            "cueIn": "0.26",
            "cueOut": "7.33"
          },
          {
            "title": "A MinoR 145 BPM Avastha 199 APC-1",
            "cueIn": "0.52",
            "cueOut": "7.56"
          },
          {
            "title": "Relativ, MoRsei Awakened (Original Mix)",
            "cueIn": "0.26",
            "cueOut": "4.31"
          },
          {
            "title": "Mindala Freedom A# Minor 145",
            "cueIn": "0.52",
            "cueOut": "8.23"
          },
          {
            "title": "Imagine Mars The Becoming (Original Mix)",
            "cueIn": "0.33",
            "cueOut": "4.57"
          },
          {
            "title": "Becker,_Avan7_Meru_C_Major2",
            "cueIn": "0.58",
            "cueOut": "7.42"
          },
          {
            "title": "Oasis Faders Adi Edit 145 to 146",
            "cueIn": "0.52",
            "cueOut": "6.23"
          },
          {
            "title": "Avan7 Biological Connection (Original Mix)",
            "cueIn": "1.32",
            "cueOut": "6.54"
          },
          {
            "title": "146BPM G# Avan7 & Br1sa - Free Soul (Adi Edit)",
            "cueIn": "1.18",
            "cueOut": "5.04"
          },
          {
            "title": "Vom - 5 Days In Sunlight 16Bit Master 05-03-2019",
            "cueIn": "0.26",
            "cueOut": "7"
          },
          {
            "title": "Outsiders,_Volcano_On_Mars_Mojigao_B_Major",
            "cueIn": "0.13",
            "cueOut": "7.55"
          },
          {
            "title": "Technical_Hitch_Mama_India_B_Major",
            "cueIn": "1.08",
            "cueOut": "7.51"
          },
          {
            "title": "Electric_Universe,_Mad_Tribe_Party_Planners_2.1_G_Major",
            "cueIn": "0.26",
            "cueOut": "7.09"
          },
          {
            "title": "Volcano Spiritual Voices (Original Mix)",
            "cueIn": "0.26",
            "cueOut": "7.2"
          },
          {
            "title": "Adi - Will Of D",
            "cueIn": "0.26",
            "cueOut": "6.31"
          }
        ]
      }
    }
  }
};
